### ISSUE TITLE
Crash right after installing the package

### ISSUE THREAD

**Issue by saif-o99** [JiriHoffmann/react-native-clusterer#10]
i installed the package normally, and i got this error when trying to run the project
![image](https://user-images.githubusercontent.com/52207667/171148202-f011b0a1-504e-4e59-9872-7de576193b98.png)

is there any steps we need to do other than npm install?
is there any requirement for this package to work?

**Comment by JiriHoffmann** [comment]
There are no other requirements for the package and should work out of the box. Have you tried running `cd android && ./gradlew clean`? You're gonna have to provide me with more info: what version of RN are you running, etc.. Or a reproducible example.
