### ISSUE TITLE
Cannot build on Android with Expo 46

### ISSUE THREAD

**Issue by ScreamZ** [JiriHoffmann/react-native-clusterer#12]
Hello,

Just migrated from expo 45 to 46, which results in react-native update too

```
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * Where:
[RUN_GRADLEW] Build file '/private/var/folders/rn/m4j774cj3kl9q8mftngq47g40000gn/T/eas-build-local-nodejs/74ada343-85fe-4672-a6e3-ba6f4f112653/build/node_modules/react-native-clusterer/android/build.gradle' line: 115
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] A problem occurred evaluating project ':react-native-clusterer'.
[RUN_GRADLEW] > Expected directory '/private/var/folders/rn/m4j774cj3kl9q8mftngq47g40000gn/T/eas-build-local-nodejs/74ada343-85fe-4672-a6e3-ba6f4f112653/build/node_modules/react-native/android' to contain exactly one file, however, it contains more than one file.
[RUN_GRADLEW] * Try:
[RUN_GRADLEW] > Run with --stacktrace option to get the stack trace.
[RUN_GRADLEW] > Run with --info or --debug option to get more log output.
[RUN_GRADLEW] > Run with --scan to get full insights.
[RUN_GRADLEW] * Get more help at https://help.gradle.org
[RUN_GRADLEW] BUILD FAILED in 18s
```

now my build fails

Is there anything I can do for help @JiriHoffmann

**Comment by ScreamZ** [comment]
@JiriHoffmann Up on that maybe you could help me ?

**Comment by JiriHoffmann** [comment]
I am guessing this might be an issue with react native v69. I am super busy at the moment, not sure when I will be able to take a closer look at it.

**Comment by ScreamZ** [comment]
Maybe some hint where I can dig on ? and try to patch myself?

**Comment by JiriHoffmann** [comment]
My suggestion would be to look at other libraries using JSI. I remember seeing some changes related to 0.69 in https://github.com/ospfranco/react-native-quick-sqlite/releases so maybe that might give you some info?

**Comment by denizmersinlioglu** [comment]
Same problem with RN 0.69.x

**Comment by JiriHoffmann** [comment]
Yes, I know about it, my motherboard was fried, so I couldn't test it out. Will take a look at it either today or tomorrow

**Comment by JiriHoffmann** [comment]
New release out, give it a try!

**Comment by ScreamZ** [comment]
Awesome, gonna check Thanks

**Comment by lucksp** [comment]
@ScreamZ is it fixed?  We need to be compatible with SDK 46

**Comment by ScreamZ** [comment]
Just checked, it builds on latest patch
