### ISSUE TITLE
[iOS] Map markers still visible on top of cluster after zooming out

### ISSUE THREAD

**Issue by henrymoulton** [JiriHoffmann/react-native-clusterer#13]
https://user-images.githubusercontent.com/30093692/185503537-68b49817-a858-4ba8-9b12-9c088b9fa2bd.mp4

Thanks for the library, it's really cool, I've noticed a bug with the example code, when you zoom back out the pins still appear. I'd expect the pins to disspear, right?

**Comment by JiriHoffmann** [comment]
Hmm... That is really odd! I've never seen this issue before and the same thing with the Google Maps issue. I'll try to take a look at it over the next weekend if I have some time.

**Comment by henrymoulton** [comment]
@JiriHoffmann I've noticed your example is running `"react-native-maps": "^0.29.4",` while I'm running `"react-native-maps": "1.1.0",`, will take a look quickly...

**Comment by henrymoulton** [comment]
Can confirm that your example does work so it's probably a problem on my end dependency wise

**Comment by henrymoulton** [comment]
I'm running `"react-native": "0.66.4",` example is `"react-native": "0.66.3",` so most likely the maps discrepancy.

**Comment by JiriHoffmann** [comment]
Yeah, that definitely could be it, it seems to be an issue with rerendering on the map rather than the clustering itself

**Comment by henrymoulton** [comment]
Looked into the release notes since `1.0` and couldn't see a good reason this would happen hmm.

**Comment by henrymoulton** [comment]
There is some mentions of a new Google Maps renderer but can't obviously this is Apple Maps, any thoughts @JiriHoffmann ?

**Comment by henrymoulton** [comment]
@JiriHoffmann I've noticed that sometimes with Storybook the clustering is fine and then when I turn off Storybook the map keeps default markers where there were previously clusters.

**Comment by henrymoulton** [comment]
I do think this is a `react-native-maps` bug, but unsure how to further debug...

**Comment by henrymoulton** [comment]
This turned out to be a bug with Reanimated.

**Comment by cjones26** [comment]
@henrymoulton what was the Reanimated bug?
