### ISSUE TITLE
[iOS] Doesn't work with Google Maps

### ISSUE THREAD

**Issue by henrymoulton** [JiriHoffmann/react-native-clusterer#14]
https://user-images.githubusercontent.com/30093692/185504145-7d74f1c4-b61d-487b-9037-74c2163d2ad0.mp4

While working as shown (sort of) with Apple Maps, it does not seem to work with Google Maps for iOS #13

**Comment by martmalo** [comment]
Try changing cluster radius in options. Documentation [here](https://github.com/JiriHoffmann/react-native-clusterer#supercluster-options).
