### ISSUE TITLE
MaxZoom not working as expected

### ISSUE THREAD

**Issue by lukeinage** [JiriHoffmann/react-native-clusterer#16]
First off, excellent library @JiriHoffmann !
However I have found that that the maxZoom option does not work the same as the regular supercluster library. This could be my use of the extent tile size prop which I could be entering incorrectly. I've tried 256, 512 and 1024. This is both iOS + Android.

minZoom: 1,
maxZoom: 18,
extent: 1024,
radius: 120

This configuration will show all markers without clustering but once zoom level 21 is reached not 18.

Extents of 256 and 512 always seem to show the clusters no matter the entered maxZoom

Expected
Once the zoom level surpasses the number all markers should be shown within the viewport without clustering

**Comment by RamonAmaro** [comment]
Is it possible to get a change in the source code with package update to make maxZoom work?
