### ISSUE TITLE
Not working on android with RN 0.71

### ISSUE THREAD

**Issue by teeserted** [JiriHoffmann/react-native-clusterer#27]
node_modules/react-native/android folder is empty and thus the following in build.gradle fails:

`
dependencies {
  //noinspection GradleDynamicVersion
  implementation 'com.facebook.react:react-native:+'
  def rnMatcher = reactNativeVersion < 69
    ? "**/**/*.aar"
    : "**/react-native/**/*${buildType()}.aar"

  def rnAAR = fileTree(reactNativePath).matching({ it.include rnMatcher }).singleFile
  extractJNI(files(rnAAR))
}`

Since there will be no .aar files.

**Comment by bisak** [comment]
I'm facing the same issue with React-Native 71 :/

**Comment by BlueIcedPen** [comment]
I can confirm, facing the same issue here. RN 0.71.2. When I install the package and build there are build issues, as soon as I remove the package and run the app, it's perfect.

**Comment by joshke** [comment]
I tried to find a solution, but my expertise is not that great with native plugins. Looks like react-native removed the aar files in the android folder.  I found some other libraries with the same issue but couldn't get any patches to work...

For example:
https://github.com/zzz08900/vision-camera-071-fix/blob/main/react-native-vision-camera%2B2.15.2.patch

Another quick and dirty approach might be to download the files manually and place them in the folder, but I couldn't find the aar files needed from the maven repository:

https://mvnrepository.com/artifact/com.facebook.react/hermes-android

**Comment by JoniVR** [comment]
See #26 and #28
