### ISSUE TITLE
Clusterer: React Native component  getLeaves

### ISSUE THREAD

**Issue by BinLei001** [JiriHoffmann/react-native-clusterer#29]
I use Clusterer as React componet. When the point is clicked, if it is a cluster, I need to get all leaves.
But Clusterer is a `FunctionComponent` I tried to use `ref`, failed.
So how do I get `superclusterer`, and then call its method to `getLeaves`?
```
 <Clusterer
      // ref={ref => {this.clusterer = ref}}  can't use ref here
      data={ clusterCollection}
      region={region}
      options={{radius: 18,minZoom:clusterMinZoom}}
      mapDimensions={MAP_DIMENSIONS}
      renderItem={(item) => {
        return (
        <Point
            key={
            item.properties?.cluster_id ?? `point-${item.properties?.id}`
            }
            item={item}
            onPress={(item) => {
            
            }}
        />
        )
    }}
  />
```

**Comment by FazilMuhammed** [comment]
@BinLei001 did you got the solution.same issue also I have when a cluster click need get details how its possible ?

**Comment by JiriHoffmann** [comment]
The `Clusterer` component is just a simple wrapper and doesn't implement a `ref`. You can either use the `getExpansionRegion()` property (before v2.0.0 it was `getClusterExpansionRegion()`) that is provided for all clusters features in both  `Clusterer` and `useClusterer`, or implement it yourself with the `Supercluster` class.
