### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by MauriFont** [JiriHoffmann/react-native-clusterer#36]
Hey.

I am new to react native, expo, pod, etc. and I am having some issues while trying to use this library.

Without using the "pod install" I get the following error:

Error: The package 'react-native-clusterer' doesn't seem to be linked. Make sure: 

- You have run 'pod install'
- You rebuilt the app after installing the package
- You are not using Expo managed workflow

Now, according to the instructions I should execute the command "cd ios && pod install" but where am I supposed to get the podfile from? I tried with the one in the example but same error is thrown.

Is this library compatible with expo?

Thank you.

**Comment by mtjkln** [comment]
the pod file is already present in ios

**Comment by JiriHoffmann** [comment]
Yes, this package works with Expo, but you will need to make a development build, it does not work with Expo Go.
