### ISSUE TITLE
Unable to use debugger while using cluster

### ISSUE THREAD

**Issue by ScreamZ** [JiriHoffmann/react-native-clusterer#4]
Hello,

Trying the lib, works very nicely, but I'm not able to use the debugger anymore while the clustered is running

![IMG_73268101A97A-1](https://user-images.githubusercontent.com/6640835/165282774-fec83a37-f0d1-4656-93f3-d7804818d2eb.jpeg)

Any idea or workaround to share?

Thanks

**Comment by JiriHoffmann** [comment]
Correct me if I am wrong, but the chrome debugger is not available when using any library with JSI. I personally haven't used it in a while now and you should probably switch to [Flipper](https://fbflipper.com/)
