### ISSUE TITLE
Performance compared to other libraries

### ISSUE THREAD

**Issue by hichemfantar** [JiriHoffmann/react-native-clusterer#41]
Can you provide some benchmarks compared to other libraries like [use-supercluster](https://github.com/leighhalliday/use-supercluster)?

Thanks

**Comment by JiriHoffmann** [comment]
Here are 2 screenshots from the example using 1000 points (which you can also run yourself and compare)

## Supercluster
![Simulator Screen Shot - iPhone 14 Pro - 2024-04-05 at 09 42 43](https://github.com/JiriHoffmann/react-native-clusterer/assets/37304278/8de68384-8afc-4bc8-9711-b36adbc0dbe2)

## react-native-clusterer
![Simulator Screen Shot - iPhone 14 Pro - 2024-04-05 at 09 43 48](https://github.com/JiriHoffmann/react-native-clusterer/assets/37304278/02783c7a-7c7a-48b3-a06c-3294e92e5fa4)
