### ISSUE TITLE
React Native 0.76 with New Architecture build fails with "No type named 'result_of' in namespace 'std'"

### ISSUE THREAD

**Issue by petetnt** [JiriHoffmann/react-native-clusterer#45]
When trying to build app with `react-native-supercluster` on React Native 0.76 with New Architecture, the build fails with the following errors:

> Error: No type named 'result_of' in namespace 'std'
> Error: Expected ';' after alias declaration

https://github.com/JiriHoffmann/react-native-clusterer/blob/ceb996a770fc34347d93a0d98453d880dd04fb65/cpp/supercluster.hpp#L346-L351

> Error: No type named 'result_of' in namespace 'std'
> Error: Expected ';' after alias declaration

https://github.com/JiriHoffmann/react-native-clusterer/blob/ceb996a770fc34347d93a0d98453d880dd04fb65/cpp/supercluster.hpp#L358-L362

Not familiar with C++ myself, but apparently `std::result_of` has been deprecated at C++17 and removed in C++20 and `invoke_result` should be used instead? [See CPP Reference](https://en.cppreference.com/w/cpp/types/result_of). Just replacing them seems to at least pass the build and the app renders the clusters.

Is that correct or am I way off? It works correctly with 0.75.3 with new architecture disabled.

**Comment by fobos531** [comment]
Hello @JiriHoffmann, I can confirm that the solution provided by @petetnt works. Would you accept a PR for this?

**Comment by JiriHoffmann** [comment]
@fobos531 if you wanna make a PR that would great. I'm busy today, but I can take a look at it over the weekend and get a new release out.

**Comment by JiriHoffmann** [comment]
Sounds good, thanks guys!
