### ISSUE TITLE
Wrong typings

### ISSUE THREAD

**Issue by ScreamZ** [JiriHoffmann/react-native-clusterer#5]
https://github.com/JiriHoffmann/react-native-clusterer/blob/65eff7e8990aab601bf77b25b916bc6ff6087380/src/types.ts#L125

In typescript types
This is at the wrong place, currently, it's defined at the same level as `properties` but this is at `properties` child level.

```json
"properties": Object {
    "cluster": true,
    "cluster_id": 40,
    "getClusterExpansionRegion": [Function getClusterExpansionRegion],
    "point_count": 4,
    "point_count_abbreviated": "4",
  },
````

**Comment by JiriHoffmann** [comment]
Fixed, thanks!
