### ISSUE TITLE
Static clusters with useClusterer hook

### ISSUE THREAD

**Issue by i-mighty** [JiriHoffmann/react-native-clusterer#8]
Below is how I'm using the useClusterer hook
`const [points, supercluster] = useClusterer(mapPoints, MAP_DIMENSIONS, region, { minPoints: 5, extent: 1000 });`
mapPoint is a state. I expect the clusterer to reload the cluster points when mapPoint changes but that doesn't happen.

**Comment by ScreamZ** [comment]
@i-mighty When region change, the cluster get recalculated, that's why you have to listen to `onRegionChange` on the MapView. About the points I can't confirm but I guess it works the same way

**Comment by JiriHoffmann** [comment]
I just double-checked and updates on both values seem to be working just fine in the example project. Make sure that you are actually updating those values or post a reproducible demo.
